site_name: Seafile User Manual
site_author: seafile
docs_dir: ./en
site_url: https://haiwen.github.io/seafile-user-manual/

repo_name: haiwen/seafile-user-manual
repo_url: https://github.com/haiwen/seafile-user-manual/
edit_uri: blob/master/en

copyright: Copyright &copy; 2020 seafile

theme:
  name: material
  # icon:
  logo: media/seafile-transparent-1024.png
  favicon: media/favicon.ico
  # features:
    # - tabs
  palette:
    primary: white
    accent:

plugins:
  - search # necessary for search to work
  - awesome-pages

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haiwen/seafile-user-manua/

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      toc_depth: "1-4"

# Page tree
nav:
  - Managing Files and Folders:
    - Managing files with libraries: file_folder_managing/libraries_managing.md
    - Restoring deleted files: file_folder_managing/restoring_deleted_files.md
    - Finding old file versions: file_folder_managing/finding_older_version_files.md
    - Library history and snapshots: file_folder_managing/library_history_and_snapshots.md
    - Setting history retention period: file_folder_managing/setting_library_history.md
    - Deleting a library: file_folder_managing/deleting_a_library.md
    - Viewing files within Web App: file_folder_managing/viewing_files_within_web_app.md
    - Full text file search: file_folder_managing/full-text_file_search.md
  - Sharing and Collaboration:
    - Sharing files and folders: sharing_collaboration/sharing_files_and_folders.md
    - Managing groups: sharing_collaboration/groups_managing.md
    - Locking files: sharing_collaboration/file_locking.md
    - Folder permission: sharing_collaboration/folder_permission.md
    - Departments Sharing: sharing_collaboration/departments.md
  - Wiki and Knowledge Management:
    - Manage Library as Wiki: wiki/manage_library_as_wiki.md
  - Metadata:
    - metadata/overview.md
    - metadata/enable_the_metadata_function.md
    - metadata/table_view.md
    - metadata/kanban_view.md
    - metadata/gallery_view.md
    - metadata/map_view.md
  - Desktop Client and Syncing:
    - Install and sync Files: syncing_client/install_sync.md
    - Syncing existing folders: syncing_client/syncing_existing_folders.md
    - Selective sync sub-folders: syncing_client/selective_sync_sub-folders.md
    - Read-only syncing: syncing_client/read-only_syncing.md
    - Unsync and resync libraries: syncing_client/unsync_and_resync_library.md
    - Setting sync interval: syncing_client/setting_sync_interval.md
    - Proxy settings: syncing_client/proxy_settings.md
    - File conflicts: syncing_client/file_conflicts.md
    - Excluding files: syncing_client/excluding_files.md
    - Install On Linux: syncing_client/install_linux_client.md
    - Seafile Client for a Cli server: syncing_client/linux-cli.md
  - Drive Client:
    - Drive Client for Windows 10 or later: drive_client/drive_client_for_win10.md
    - Drive Client for macOS: drive_client/drive_client_for_macos.md
    - Drive Client for Linux: drive_client/drive_client_for_linux.md
  - Security and Encryption:
    - How to use encrypted libraries: security_and_encryption/use_encrypted_libraries.md
  - Organization Management:
    - Daily Management: organization_management/daily_management.md
    - Integration with ADFS/SAML: organization_management/integration_with_ADFS_SAML.md
  - FAQ: faq.md
